version: '3.8'
services:
  django:
    build:
      context: ./Dockerfile/django
      dockerfile: Dockerfile
    volumes:
      - ./sources:/home/user/sources
      - static_volume:/home/user/sources/staticfiles
      - media_volume:/home/user/sources/mediafiles
    tty: true
    environment:
      TZ: ${TZ}
      LANG: ${LANG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEVELOP: ${DEVELOP}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
      - selenium
    networks:
      - web_network

  mysql:
    build:
      context: ./Dockerfile/mysql
      dockerfile: Dockerfile
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      TZ: ${TZ}
      LANG: ${LANG}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    networks:
      - web_network

  selenium:
    image: selenium/standalone-chrome
    # ports:
    #   - 4444:4444
    #   - 7900:7900
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - web_network

  phpmyadmin:
    build:
      context: ./Dockerfile/phpmyadmin
      dockerfile: Dockerfile
    # ports:
    #   - 8080:80
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - web_network

  nginx:
    build:
      context: ./Dockerfile/nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    tty: true
    volumes:
      - ./Dockerfile/nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - static_volume:/home/user/sources/staticfiles
      - media_volume:/home/user/sources/mediafiles
    depends_on:
      - django
      - selenium
      - phpmyadmin
    networks:
      - web_network

volumes:
  mysql_data:
  static_volume:
  media_volume:


networks:
  web_network:
