version: '3.8'
services:
  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    image: my_django_app
    volumes:
      - ./django/sources:/sources
    tty: true
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - mysql
      - selenium
    networks:
      - web_network

  cron:
    build:
      context: ./cron
      dockerfile: Dockerfile
    image: my_cron_app
    env_file:
      - .env
    networks:
      - web_network

  mysql:
    image: mysql:8.0.36
    volumes:
      - mysql_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    env_file:
      - .env
    networks:
      - web_network

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
      - 7900:7900
    volumes:
      - /dev/shm:/dev/shm
    env_file:
      - .env
    networks:
      - web_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    env_file:
      - .env
    networks:
      - web_network

volumes:
  mysql_data:

networks:
  web_network:
