# Generated by Django 5.0.4 on 2024-04-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0009_remove_eventargs_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrapeCategory',
            new_name='EventCategory',
        ),
    ]
