# Generated by Django 5.0.6 on 2024-07-15 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('web_netkeiba_pagesources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseRacingTipAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='予想家名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='HorseRacingTipMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=255, verbose_name='印')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='HorseRacingTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_id', models.PositiveIntegerField()),
                ('race_id', models.CharField(max_length=255, verbose_name='レースID')),
                ('horse_number', models.IntegerField(verbose_name='馬番')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('parser_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_netkeiba_tips.horseracingtipmark', verbose_name='印')),
            ],
        ),
        migrations.CreateModel(
            name='HorseRacingTipParserForPageYoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_update_at', models.DateTimeField(null=True, verbose_name='次回更新日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('page_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_netkeiba_pagesources.pageyoso', verbose_name='取得元ページ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HorseRacingTipParserForPageYosoCp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_update_at', models.DateTimeField(null=True, verbose_name='次回更新日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('page_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_netkeiba_pagesources.pageyosocp', verbose_name='取得元ページ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HorseRacingTipParserForPageYosoPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_update_at', models.DateTimeField(null=True, verbose_name='次回更新日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('page_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_netkeiba_pagesources.pageyosopro', verbose_name='取得元ページ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
