# Generated by Django 5.0.6 on 2024-07-15 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_netkeiba_tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horseracingtip',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='db_netkeiba_tips.horseracingtipauthor', verbose_name='予想家'),
            preserve_default=False,
        ),
    ]
