# Generated by Django 5.0.7 on 2024-07-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_netkeiba_tips', '0002_horseracingtip_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='horseracingtipparserforpageyoso',
            name='success_parsing',
            field=models.BooleanField(default=False, verbose_name='パース成功フラグ'),
        ),
        migrations.AddField(
            model_name='horseracingtipparserforpageyosocp',
            name='success_parsing',
            field=models.BooleanField(default=False, verbose_name='パース成功フラグ'),
        ),
        migrations.AddField(
            model_name='horseracingtipparserforpageyosopro',
            name='success_parsing',
            field=models.BooleanField(default=False, verbose_name='パース成功フラグ'),
        ),
    ]
