# Generated by Django 5.0.6 on 2024-07-07 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db_netkeiba_races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseRacingTicketName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='馬券名')),
                ('description', models.TextField(verbose_name='説明')),
            ],
        ),
        migrations.CreateModel(
            name='HorseRacingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiguous_name', models.CharField(max_length=255, verbose_name='あいまいな馬券名')),
                ('win_str', models.CharField(max_length=255, verbose_name='当選条件')),
                ('first', models.IntegerField(verbose_name='1着')),
                ('second', models.IntegerField(verbose_name='2着')),
                ('third', models.IntegerField(verbose_name='3着')),
                ('refund', models.IntegerField(verbose_name='払戻金')),
                ('netkeiba_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_netkeiba_races.netkeibarace', verbose_name='レース')),
                ('official_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_netkeiba_tickets.horseracingticketname', verbose_name='馬券名')),
            ],
        ),
    ]
