# Generated by Django 5.0.6 on 2024-07-08 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_netkeiba_pagesources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseRacingTicketName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='馬券名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='HorseRacingTicketParser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_update_at', models.DateTimeField(null=True, verbose_name='次回更新日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('page_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_netkeiba_pagesources.pageresult', verbose_name='取得元ページ')),
            ],
        ),
        migrations.CreateModel(
            name='HorseRacingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(max_length=255, verbose_name='レースID')),
                ('ambiguous_name', models.CharField(max_length=255, verbose_name='あいまいな馬券名')),
                ('win_str', models.CharField(max_length=255, verbose_name='当選条件')),
                ('first', models.IntegerField(verbose_name='1着')),
                ('second', models.IntegerField(verbose_name='2着')),
                ('third', models.IntegerField(verbose_name='3着')),
                ('refund', models.IntegerField(verbose_name='払戻金')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('official_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_netkeiba_tickets.horseracingticketname', verbose_name='馬券名')),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_netkeiba_tickets.horseracingticketparser', verbose_name='取得元')),
            ],
        ),
    ]
