# Generated by Django 5.0.6 on 2024-07-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_netkeiba_tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horseracingticket',
            name='first',
        ),
        migrations.RemoveField(
            model_name='horseracingticket',
            name='second',
        ),
        migrations.RemoveField(
            model_name='horseracingticket',
            name='third',
        ),
    ]
