# Generated by Django 5.0.7 on 2024-07-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_netkeiba_tickets', '0002_remove_horseracingticket_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horseracingticketparser',
            name='success_parsing',
            field=models.BooleanField(default=False, verbose_name='パース成功フラグ'),
        ),
    ]
