# Generated by Django 5.0.7 on 2024-07-21 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_netkeiba_tickets', '0003_horseracingticketparser_success_parsing'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseRacingTicketTouchNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_number', models.IntegerField(verbose_name='馬番号')),
                ('ticket_number_order', models.IntegerField(verbose_name='馬券内順序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_netkeiba_tickets.horseracingticket', verbose_name='馬券')),
            ],
            options={
                'unique_together': {('ticket', 'horse_number', 'ticket_number_order')},
            },
        ),
    ]
