# Generated by Django 5.0.4 on 2024-04-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_rename_scrapingschedule_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
