# Generated by Django 5.0.4 on 2024-04-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_schedule_memo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='CrawlSchedule',
        ),
    ]
