# Generated by Django 5.0.4 on 2024-04-12 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_rename_schedule_crawlschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='crawlschedule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scraping.scrapecategory'),
        ),
        migrations.AddField(
            model_name='crawlschedule',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='scraping.crawlstatus'),
        ),
    ]
