# Generated by Django 5.0.4 on 2024-04-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_crawlstatus_alter_crawlschedule_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrawlSchedule',
            new_name='EventSchedule',
        ),
        migrations.RenameModel(
            old_name='CrawlStatus',
            new_name='EventStatus',
        ),
        migrations.AlterField(
            model_name='scrapecategory',
            name='use_method',
            field=models.CharField(default='default_methods', max_length=255),
        ),
    ]
