# Generated by Django 5.0.4 on 2024-04-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_rename_crawlschedule_eventschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapecategory',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
    ]
