# Generated by Django 5.0.4 on 2024-04-12 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_scrapecategory_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='status',
            field=models.IntegerField(choices=[(1, '待機'), (2, '実行中'), (3, '完了'), (4, 'エラー')], default=1),
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='url',
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='errormessage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='EventArgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scraping.eventschedule')),
            ],
        ),
        migrations.DeleteModel(
            name='EventStatus',
        ),
    ]
