# Generated by Django 5.0.4 on 2024-04-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0008_alter_eventschedule_status_remove_eventschedule_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventargs',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='scrapecategory',
            name='need_driver',
            field=models.BooleanField(default=False),
        ),
    ]
