# Generated by Django 5.0.4 on 2024-04-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0010_rename_scrapecategory_eventcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='durationtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='enddatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='latestexecuted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='startdatetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
