# Generated by Django 5.0.4 on 2024-04-12 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0011_eventschedule_durationtime_eventschedule_enddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='latestexecuted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='startdatetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
