# Generated by Django 5.0.4 on 2024-04-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0013_htmldocuments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HtmlDocuments',
        ),
    ]
