# Generated by Django 5.0.4 on 2024-04-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0015_htmldocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmldocuments',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
    ]
