# Generated by Django 5.0.4 on 2024-04-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0019_alter_logininfo_cookie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginInfo',
        ),
    ]
