# Generated by Django 5.0.6 on 2024-07-06 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_netkeiba_pagesources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetkeibaRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(max_length=255, verbose_name='レースID')),
                ('page_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_netkeiba_pagesources.page', verbose_name='ページソース')),
            ],
        ),
    ]
