# Generated by Django 5.1.3 on 2024-11-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginforscraping',
            name='cookie',
            field=models.JSONField(default=list),
        ),
    ]
