# Generated by Django 5.0.4 on 2024-05-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='html',
        ),
        migrations.AddField(
            model_name='shutuba',
            name='html',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
