# Generated by Django 5.0.4 on 2024-04-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrapingSchedule',
            new_name='Schedule',
        ),
    ]
