# Generated by Django 5.0.4 on 2024-05-06 05:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageOikiri',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scraping.page')),
                ('html', models.BinaryField(blank=True, null=True)),
            ],
            bases=('scraping.page',),
        ),
        migrations.CreateModel(
            name='PageYoso',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scraping.page')),
                ('html', models.BinaryField(blank=True, null=True)),
            ],
            bases=('scraping.page',),
        ),
        migrations.CreateModel(
            name='PageYosoCp',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scraping.page')),
                ('html_1', models.BinaryField(blank=True, null=True)),
                ('html_2', models.BinaryField(blank=True, null=True)),
                ('html_3', models.BinaryField(blank=True, null=True)),
                ('html_4', models.BinaryField(blank=True, null=True)),
                ('html_5', models.BinaryField(blank=True, null=True)),
                ('html_6', models.BinaryField(blank=True, null=True)),
            ],
            bases=('scraping.page',),
        ),
        migrations.CreateModel(
            name='PageYosoPro',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scraping.page')),
                ('html', models.BinaryField(blank=True, null=True)),
            ],
            bases=('scraping.page',),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='schedule_str',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='nextexecutedatetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='schedule_str',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
