# Generated by Django 5.0.4 on 2024-05-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_pageoikiri_pageyoso_pageyosocp_pageyosopro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageyosocp',
            old_name='html_1',
            new_name='html_jockey',
        ),
        migrations.RenameField(
            model_name='pageyosocp',
            old_name='html_2',
            new_name='html_pedigree',
        ),
        migrations.RenameField(
            model_name='pageyosocp',
            old_name='html_3',
            new_name='html_precede',
        ),
        migrations.RenameField(
            model_name='pageyosocp',
            old_name='html_4',
            new_name='html_rising',
        ),
        migrations.RenameField(
            model_name='pageyosocp',
            old_name='html_5',
            new_name='html_spurt',
        ),
        migrations.RenameField(
            model_name='pageyosocp',
            old_name='html_6',
            new_name='html_trainer',
        ),
    ]
