# Generated by Django 5.0.4 on 2024-05-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_remove_eventcategory_durationtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategory',
            name='repeat',
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='repeat',
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='schedule_str',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='schedule_str',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
