# Generated by Django 5.0.4 on 2024-04-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_raceid_raceidcategory_shutuba_delete_cookieforlogin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raceid',
            old_name='raceid',
            new_name='race_id',
        ),
        migrations.RenameField(
            model_name='shutuba',
            old_name='raceid',
            new_name='race_id',
        ),
    ]
