# Generated by Django 5.0.6 on 2024-05-25 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_alter_eventschedule_schedule_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventErrorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errormessage', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scraping.eventschedule')),
            ],
        ),
    ]
