# Generated by Django 5.0.4 on 2024-04-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_rename_raceid_raceid_race_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventschedule',
            name='durationtime',
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='durationtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
