# Generated by Django 5.0.4 on 2024-05-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_remove_eventcategory_repeat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='schedule_str',
            field=models.CharField(default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='schedule_str',
            field=models.CharField(default='0', max_length=255, null=True),
        ),
    ]
