# Generated by Django 5.0.4 on 2024-04-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_remove_eventschedule_durationtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='latestexecuted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
