# Generated by Django 5.0.4 on 2024-04-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_alter_eventschedule_latestexecuted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='latestcalled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
