# Generated by Django 5.0.4 on 2024-04-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0018_logininfo_alter_eventcategory_use_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='cookie',
            field=models.BinaryField(default=b''),
        ),
    ]
