# Generated by Django 5.0.4 on 2024-04-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0021_loginrequired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginrequired',
            name='login_url',
        ),
        migrations.RemoveField(
            model_name='loginrequired',
            name='password',
        ),
        migrations.RemoveField(
            model_name='loginrequired',
            name='username',
        ),
    ]
