# Generated by Django 5.0.4 on 2024-04-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0023_remove_loginrequired_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginRequired',
            new_name='LoginForScraping',
        ),
    ]
