# Generated by Django 5.0.4 on 2024-04-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0024_rename_loginrequired_loginforscraping'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='parallel_limit',
            field=models.IntegerField(default=1),
        ),
    ]
