# Generated by Django 5.0.7 on 2024-07-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_netkeiba_pagesources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='need_update',
            field=models.BooleanField(default=False),
        ),
    ]
