# Generated by Django 5.0.6 on 2024-07-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_str_default',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='title',
        ),
    ]
