# Generated by Django 5.0.6 on 2024-07-06 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_netkeiba_race', '0001_initial'),
        ('db_netkeiba_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horseracingticket',
            name='race',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='db_netkeiba_race.netkeibarace', verbose_name='レース'),
            preserve_default=False,
        ),
    ]
