# Generated by Django 5.0.7 on 2024-07-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db_netkeiba_tickets', '0004_horseracingtickettouchnumber'),
        ('db_netkeiba_tips', '0003_horseracingtipparserforpageyoso_success_parsing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseRacingTouchTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_netkeiba_tickets.horseracingticket')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_netkeiba_tips.horseracingtip')),
            ],
        ),
    ]
