# Generated by Django 5.0.7 on 2024-07-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_tips_refund_rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horseracingtouchtip',
            name='race_id',
            field=models.CharField(default='tip.race_id', max_length=255),
        ),
        migrations.AddField(
            model_name='horseracingtouchtip',
            name='touch_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
