# Generated by Django 5.0.7 on 2024-07-21 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_netkeiba_tips', '0003_horseracingtipparserforpageyoso_success_parsing_and_more'),
        ('logic_tips_refund_rates', '0002_horseracingtouchtip_race_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horseracingtouchtip',
            name='race_id',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='HorseRacingTouchTipManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_netkeiba_tips.horseracingtip')),
            ],
        ),
    ]
