# Generated by Django 5.0.7 on 2024-07-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_tips_refund_rates', '0003_alter_horseracingtouchtip_race_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseRacingTipRefundManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(max_length=255, verbose_name='レースID')),
            ],
        ),
        migrations.RemoveField(
            model_name='horseracingtouchtipmanager',
            name='tip',
        ),
        migrations.DeleteModel(
            name='HorseRacingTouchTip',
        ),
        migrations.DeleteModel(
            name='HorseRacingTouchTipManager',
        ),
    ]
