# Generated by Django 5.0.7 on 2024-07-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_tips_refund_rates', '0004_horseracingtiprefundmanager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horseracingtiprefundmanager',
            name='need_update',
            field=models.BooleanField(default=True, verbose_name='更新が必要かどうか'),
        ),
    ]
