# ベースイメージとしてphpmyadminの公式イメージを使用
FROM phpmyadmin/phpmyadmin

# # 環境変数を設定
# ENV APACHE_SERVER_NAME="localhost"

# # Apache設定ファイルにServerNameディレクティブを追加
# # phpmyadminの設定ファイルを修正
# RUN echo "ServerName ${APACHE_SERVER_NAME}" >> /etc/apache2/apache2.conf

# # 必要に応じて追加の設定やコピー処理を行います

# # コンテナ内でApacheを実行
# CMD ["apache2-foreground"]
