# Generated by Django 5.0.7 on 2024-08-01 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db_netkeiba_tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseRacingTipRefundManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(max_length=255, unique=True, verbose_name='レースID')),
                ('need_update', models.BooleanField(default=True, verbose_name='更新が必要かどうか')),
            ],
        ),
        migrations.CreateModel(
            name='HorseRacingTipRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(max_length=255, verbose_name='レースID')),
                ('amount', models.IntegerField(verbose_name='使用金額')),
                ('refund', models.IntegerField(verbose_name='払戻金額')),
                ('predictions', models.JSONField(default=dict, verbose_name='予想')),
                ('ticket_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_netkeiba_tickets.horseracingticketcategory', verbose_name='馬券')),
            ],
        ),
    ]
