# Generated by Django 5.0.7 on 2024-08-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_tips_refund_rates', '0002_rename_ticket_name_horseracingtiprefund_ticket_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horseracingtiprefund',
            name='amount',
        ),
        migrations.AddField(
            model_name='horseracingtiprefund',
            name='count',
            field=models.IntegerField(default=0, verbose_name='購入数'),
            preserve_default=False,
        ),
    ]
