# Generated by Django 5.0.6 on 2024-06-22 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDoeventHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variables', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_schedules.schedule')),
            ],
        ),
        migrations.DeleteModel(
            name='ScheduleDoEventError',
        ),
    ]
