# Generated by Django 5.0.6 on 2024-06-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_schedules', '0002_scheduledoeventhistory_delete_scheduledoeventerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledoeventhistory',
            name='event_function',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
