name: Deploy to K3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker registry (Optional if you're using a private registry)
      #- name: Log in to Docker registry
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t django:latest ./Dockerfile/django
          docker build -t cron:latest ./Dockerfile/cron

      # Tag Docker image
      - name: Tag Docker image
        run: |
          docker tag django:latest localhost:5000/django:latest
          docker tag cron:latest localhost:5000/cron:latest

      # Push Docker image to registry
      - name: Push Docker image
        run: |
          docker push localhost:5000/django:latest
          docker push localhost:5000/cron:latest

      # Set up kubectl
      - name: Set up kubectl
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl version --client

      # Deploy to K3s
      - name: Deploy to K3s
        run: |
          kubectl apply -f deployment.yaml